[workspace]
exclude = [
    "examples"
]

[package]
name = "solana-bpf-simulator"
version = "0.1.2"
edition = "2021"

[[bin]]
name = "solana-bpf-simulator"
path = "src/main.rs"

[dependencies]
anyhow = "1"
bincode = "1"
bs58 = "0.4"
clap = {version = "~4.1", features = ["derive", "env"]}
fehler = "1"
getset = "0.1"
once_cell = "1"
serde = "1"
solana-bpf-loader-program = "~1.16"
solana-client = "~1.16"
solana-program-runtime = "~1.16"
solana-runtime = "~1.16"
solana-sdk = "~1.16"
solana-zk-token-sdk = "~1.16"
solana_rbpf = "~0.6"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "registry"] }
url = "2"

# [patch.crates-io]
# solana-bpf-loader-program = { path = "../solana-mole/programs/bpf_loader" }
# solana-client = { path = "../solana-mole/client" }
# solana-program-runtime = { path = "../solana-mole/program-runtime" }
# solana-program = { path = "../solana-mole/sdk/program" }
# solana-runtime = { path = "../solana-mole/runtime" }
# solana-sdk = { path = "../solana-mole/sdk" }
