name: build

on:
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
          apt-get update
          apt-get install -y libssl-dev pkg-config gcc wget git

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          default: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - uses: actions/upload-artifact@v3
        with:
          name: solana-simulator-simulate-linux-x86_64
          path: target/release/simulate

      - uses: actions/upload-artifact@v3
        with:
          name: solana-simulator-get-program-data-linux-x86_64
          path: target/release/get_program_data
  macos:
    runs-on: macos-latest
    steps:
      # - name: Install tools
      #   run: |
      #     apt-get update
      #     apt-get install -y libssl-dev pkg-config gcc wget git

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          default: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - uses: actions/upload-artifact@v3
        with:
          name: solana-simulator-simulate-darwin-x86_64
          path: target/release/simulate
      - uses: actions/upload-artifact@v3
        with:
          name: solana-simulator-get-program-data-darwin-x86_64
          path: target/release/get_program_data
